name: gouziyun_daka
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: process
      env:
        EMAIL1: ${{ secrets.EMAIL1 }}
        PASSWORD1: ${{ secrets.PASSWORD1 }}
        EMAIL2: ${{ secrets.EMAIL2 }}
        PASSWORD2: ${{ secrets.PASSWORD2 }}
      run: |
        python3 test.py "$EMAIL1" "$PASSWORD1" "$EMAIL2" "$PASSWORD2"
        
