name: gouziyun_daka
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip3 install requests
        pip3 install bs4
        pip3 install lxml
    - name: process
      run: |
        python3 test.py
        
